"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { UserButton, useUser } from "@clerk/nextjs";
import { ArrowDownRight, ArrowUpRight, BarChart3, Bell, CalendarDays, CarFront, Check, ChevronRight, CircleDollarSign, Clock3, FileText, Fuel, Gauge, History, Home, Menu, MoreHorizontal, Plus, ReceiptText, Settings, Target, TrendingUp, WalletCards, Wrench, X } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Toaster } from "@/components/ui/sonner";

type Entry = { id: string; type: "gain" | "expense"; amount: number; category: string; app?: string; date: string; km?: number; hours?: number };
type AppState = { entries: Entry[]; dailyGoal: number; weeklyGoal: number; monthlyFixed: number; maintenancePerKm: number; depreciationPerKm: number; annualRevenueBeforeApp: number; vehicle: string };
const today = "2026-09-24";
const initialState: AppState = {
  dailyGoal: 200, weeklyGoal: 1100, monthlyFixed: 760, maintenancePerKm: .12, depreciationPerKm: .1, annualRevenueBeforeApp: 35420, vehicle: "Chevrolet Onix 2021",
  entries: [
    { id: "g1", type: "gain", amount: 184, category: "Corridas", app: "Uber", date: today, hours: 4.5, km: 98 },
    { id: "g2", type: "gain", amount: 136, category: "Corridas", app: "99", date: today, hours: 3.5, km: 82 },
    { id: "e1", type: "expense", amount: 90, category: "Combustível", date: today },
    { id: "e2", type: "expense", amount: 14, category: "Pedágio", date: today },
    { id: "g3", type: "gain", amount: 286, category: "Corridas", app: "Uber", date: "2026-09-23", hours: 7.2, km: 164 },
    { id: "e3", type: "expense", amount: 84, category: "Combustível", date: "2026-09-23" },
    { id: "g4", type: "gain", amount: 248, category: "Corridas", app: "99", date: "2026-09-22", hours: 6.8, km: 143 },
    { id: "e4", type: "expense", amount: 76, category: "Combustível", date: "2026-09-22" },
  ],
};
const money = (v: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(v);
const shortDate = (v: string) => new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short" }).format(new Date(`${v}T12:00:00`));
function summaryOf(state: AppState, date?: string) {
  const entries = date ? state.entries.filter(e => e.date === date) : state.entries;
  const gains = entries.filter(e => e.type === "gain").reduce((s, e) => s + e.amount, 0);
  const expenses = entries.filter(e => e.type === "expense").reduce((s, e) => s + e.amount, 0);
  const km = entries.filter(e => e.type === "gain").reduce((s, e) => s + (e.km || 0), 0);
  const hours = entries.filter(e => e.type === "gain").reduce((s, e) => s + (e.hours || 0), 0);
  const wear = km * (state.maintenancePerKm + state.depreciationPerKm);
  const fixed = date ? state.monthlyFixed / 26 : state.monthlyFixed;
  return { gains, expenses, km, hours, wear, fixed, profit: gains - expenses - wear - fixed };
}

declare global { interface Document { modelContext?: { registerTool: (tool: Record<string, unknown>, options?: { signal?: AbortSignal }) => void | Promise<void> } } }

export default function Dashboard() {
  const { user } = useUser();
  const firstName = user?.firstName || "motorista";
  const [state, setState] = useState(initialState);
  const [active, setActive] = useState("today");
  const [dialog, setDialog] = useState(false);
  const [entryType, setEntryType] = useState<"gain" | "expense">("gain");
  const [saving, setSaving] = useState(false);
  const [menu, setMenu] = useState(false);
  const persist = useCallback(async (next: AppState) => {
    setSaving(true);
    try { localStorage.setItem("lucro-no-volante-state", JSON.stringify(next)); }
    catch { toast.error("Não foi possível salvar agora", { description: "Os dados continuam nesta tela." }); }
    finally { window.setTimeout(() => setSaving(false), 250); }
  }, []);
  useEffect(() => {
    try {
      const saved = localStorage.getItem("lucro-no-volante-state");
      if (saved) {
        const parsed = JSON.parse(saved) as AppState;
        if (Array.isArray(parsed.entries)) setState(parsed);
      }
    } catch { /* Mantém os dados de demonstração se o armazenamento estiver indisponível. */ }
  }, []);
  const addEntry = useCallback((entry: Omit<Entry, "id">) => {
    const next = { ...state, entries: [{ ...entry, id: crypto.randomUUID() }, ...state.entries] };
    setState(next); void persist(next); toast.success(entry.type === "gain" ? "Ganho registrado" : "Gasto registrado");
  }, [persist, state]);
  useEffect(() => {
    const context = document.modelContext; if (!context?.registerTool) return; const lifecycle = new AbortController();
    void Promise.resolve(context.registerTool({
      name: "registrar_lancamento", title: "Registrar ganho ou gasto", description: "Registra um lançamento e atualiza o painel visível.",
      inputSchema: { type: "object", properties: { tipo: { type: "string", enum: ["ganho", "gasto"] }, valor: { type: "number", minimum: .01 }, categoria: { type: "string" }, aplicativo: { type: "string" } }, required: ["tipo", "valor", "categoria"], additionalProperties: false },
      annotations: { readOnlyHint: false, untrustedContentHint: false },
      execute: async (raw: unknown) => { const v = raw as { tipo?: string; valor?: number; categoria?: string; aplicativo?: string }; if (!v.valor || v.valor <= 0 || !v.categoria || !["ganho", "gasto"].includes(v.tipo || "")) throw new Error("Informe tipo, valor e categoria."); addEntry({ type: v.tipo === "ganho" ? "gain" : "expense", amount: v.valor, category: v.categoria, app: v.aplicativo, date: today }); return { registrado: true, valor: v.valor, tipo: v.tipo }; }
    }, { signal: lifecycle.signal })).catch(() => undefined);
    return () => lifecycle.abort();
  }, [addEntry]);
  const summary = useMemo(() => summaryOf(state, today), [state]);
  const progress = Math.min(100, Math.max(0, summary.profit / state.dailyGoal * 100));
  const revenue = state.annualRevenueBeforeApp + state.entries.filter(e => e.type === "gain").reduce((s, e) => s + e.amount, 0);
  const navigate = (page: string) => { setActive(page); setMenu(false); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const openEntry = (type: "gain" | "expense") => { setEntryType(type); setDialog(true); };
  return <div className="min-h-screen bg-[#f3f5f2] text-[#10221c]">
    <Toaster position="top-center" richColors />
    <aside className="fixed inset-y-0 left-0 z-40 hidden w-[252px] flex-col bg-[#11251f] px-5 py-6 text-white lg:flex">
      <Brand /><nav className="mt-10 space-y-1"><Nav active={active === "today"} icon={Home} label="Hoje" onClick={() => navigate("today")} /><Nav active={active === "history"} icon={History} label="Histórico" onClick={() => navigate("history")} /><Nav active={active === "mei"} icon={ReceiptText} label="Meu MEI" onClick={() => navigate("mei")} /><Nav active={active === "settings"} icon={Settings} label="Configurações" onClick={() => navigate("settings")} /></nav>
      <div className="mt-auto rounded-[22px] bg-[#1d382f] p-4"><div className="flex items-center gap-2 text-sm font-bold"><Target className="size-4 text-[#c8ff39]" /> Meta da semana</div><p className="mt-3 text-2xl font-black">{money(704)}</p><p className="text-sm text-white/55">de {money(state.weeklyGoal)}</p><Progress value={64} className="mt-3 bg-white/10 [&_[data-slot=progress-indicator]]:bg-[#c8ff39]" /></div>
    </aside>
    <main className="min-h-screen pb-24 lg:ml-[252px] lg:pb-8">
      <header className="sticky top-0 z-30 flex h-[72px] items-center justify-between border-b border-[#dce2dd] bg-[#f3f5f2]/90 px-4 backdrop-blur-xl sm:px-7 lg:h-[84px] lg:px-10"><div className="flex items-center gap-3"><Button variant="ghost" size="icon" className="lg:hidden" onClick={() => setMenu(true)} aria-label="Abrir menu"><Menu className="size-6" /></Button><div className="lg:hidden"><Brand compact /></div><div className="hidden lg:block"><p className="text-sm font-semibold text-[#64726c]">Quinta-feira, 24 de setembro</p><h1 className="text-2xl font-black tracking-[-.04em]">Boa tarde, {firstName}.</h1></div></div><div className="flex items-center gap-2"><span className="hidden items-center gap-2 rounded-full bg-white px-3 py-2 text-xs font-bold text-[#53635c] shadow-sm sm:flex"><span className={`size-2 rounded-full ${saving ? "bg-amber-400" : "bg-[#63c174]"}`} />{saving ? "Salvando" : "Tudo salvo"}</span><Button variant="outline" size="icon" className="rounded-full bg-white" aria-label="Notificações"><Bell className="size-5" /></Button><UserButton /></div></header>
      <div className="mx-auto max-w-[1240px] px-4 py-6 sm:px-7 lg:px-10 lg:py-9">{active === "today" && <Today state={state} summary={summary} progress={progress} openEntry={openEntry} firstName={firstName} />}{active === "history" && <HistoryView state={state} />}{active === "mei" && <MeiView revenue={revenue} />}{active === "settings" && <SettingsView state={state} onChange={next => { setState(next); void persist(next); }} />}</div>
    </main>
    <div className="fixed inset-x-3 bottom-3 z-40 grid grid-cols-5 rounded-[22px] bg-[#11251f] p-1.5 text-white shadow-2xl lg:hidden"><MobileNav icon={Home} label="Hoje" active={active === "today"} onClick={() => navigate("today")} /><MobileNav icon={History} label="Histórico" active={active === "history"} onClick={() => navigate("history")} /><button onClick={() => openEntry("gain")} className="mx-auto grid size-12 -translate-y-4 place-items-center rounded-full bg-[#c8ff39] text-[#11251f]" aria-label="Registrar"><Plus /></button><MobileNav icon={ReceiptText} label="MEI" active={active === "mei"} onClick={() => navigate("mei")} /><MobileNav icon={MoreHorizontal} label="Mais" active={active === "settings"} onClick={() => navigate("settings")} /></div>
    {menu && <div className="fixed inset-0 z-50 bg-[#11251f] p-6 text-white lg:hidden"><div className="flex items-center justify-between"><Brand /><Button variant="ghost" size="icon" className="text-white" onClick={() => setMenu(false)}><X /></Button></div><nav className="mt-10 space-y-2"><Nav active={active === "today"} icon={Home} label="Hoje" onClick={() => navigate("today")} /><Nav active={active === "history"} icon={History} label="Histórico" onClick={() => navigate("history")} /><Nav active={active === "mei"} icon={ReceiptText} label="Meu MEI" onClick={() => navigate("mei")} /><Nav active={active === "settings"} icon={Settings} label="Configurações" onClick={() => navigate("settings")} /></nav></div>}
    <EntryDialog open={dialog} type={entryType} onTypeChange={setEntryType} onOpenChange={setDialog} onSave={addEntry} />
  </div>;
}

function Brand({ compact = false }: { compact?: boolean }) { return <div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-[14px] bg-[#c8ff39] text-[#11251f]"><Gauge className="size-6" strokeWidth={2.6} /></div>{!compact && <div><p className="font-black leading-4">Lucro no</p><p className="font-black leading-4 text-[#c8ff39]">Volante</p></div>}</div>; }
function Nav({ icon: Icon, label, active, onClick }: { icon: typeof Home; label: string; active: boolean; onClick: () => void }) { return <button onClick={onClick} className={`flex w-full items-center gap-3 rounded-2xl px-4 py-3.5 text-sm font-bold ${active ? "bg-[#c8ff39] text-[#11251f]" : "text-white/65 hover:bg-white/10 hover:text-white"}`}><Icon className="size-5" />{label}</button>; }
function MobileNav({ icon: Icon, label, active, onClick }: { icon: typeof Home; label: string; active: boolean; onClick: () => void }) { return <button onClick={onClick} className={`flex min-w-0 flex-col items-center gap-1 rounded-2xl py-2 text-[10px] font-bold ${active ? "text-[#c8ff39]" : "text-white/50"}`}><Icon className="size-5" /><span className="truncate">{label}</span></button>; }

function Today({ state, summary, progress, openEntry, firstName }: { state: AppState; summary: ReturnType<typeof summaryOf>; progress: number; openEntry: (type: "gain" | "expense") => void; firstName: string }) {
  const perHour = summary.hours ? summary.profit / summary.hours : 0, perKm = summary.km ? summary.profit / summary.km : 0, totalCosts = summary.expenses + summary.wear + summary.fixed;
  return <><div className="mb-5 lg:hidden"><p className="text-sm font-semibold text-[#64726c]">Quinta-feira, 24 de setembro</p><h1 className="text-2xl font-black tracking-[-.04em]">Boa tarde, {firstName}.</h1></div><div className="grid gap-5 xl:grid-cols-[1.45fr_.8fr]">
    <section className="relative overflow-hidden rounded-[28px] bg-[#11251f] p-5 text-white shadow-[0_16px_50px_rgba(17,37,31,.14)] sm:p-7 lg:p-9"><div className="absolute right-[-60px] top-[-80px] size-64 rounded-full border-[45px] border-[#c8ff39]/8" /><div className="relative flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-sm font-bold text-white/55">Lucro estimado hoje</div><p className="mt-3 text-[clamp(2.7rem,7vw,4.6rem)] font-black leading-none tracking-[-.065em]">{money(Math.max(0, summary.profit))}</p><p className="mt-3 flex items-center gap-2 text-sm font-semibold text-[#c8ff39]"><TrendingUp className="size-4" /> R$ 24,50 acima de ontem</p></div><div className="rounded-2xl bg-white/7 px-4 py-3 text-right"><p className="text-xs font-bold uppercase tracking-wider text-white/45">Meta do dia</p><p className="mt-1 text-xl font-black">{Math.round(progress)}%</p></div></div><Progress value={progress} className="relative mt-7 h-3 bg-white/10 [&_[data-slot=progress-indicator]]:bg-[#c8ff39]" /><div className="relative mt-3 flex justify-between text-sm font-semibold text-white/55"><span>{money(Math.max(0, summary.profit))}</span><span>{money(state.dailyGoal)}</span></div><div className="relative mt-8 grid grid-cols-2 gap-3 border-t border-white/10 pt-6 sm:grid-cols-4"><DarkMetric label="Ganhos" value={money(summary.gains)} icon={ArrowUpRight} tone="lime" /><DarkMetric label="Gastos pagos" value={money(summary.expenses)} icon={ArrowDownRight} tone="amber" /><DarkMetric label="Por hora" value={money(perHour)} icon={Clock3} /><DarkMetric label="Por km" value={money(perKm)} icon={CarFront} /></div></section>
    <section className="rounded-[28px] bg-[#ffd44d] p-5 sm:p-7"><div className="flex items-start justify-between"><div><p className="text-sm font-black uppercase tracking-wider text-[#3d3514]/60">Fechamento rápido</p><h2 className="mt-1 text-2xl font-black tracking-[-.04em]">O que entrou ou saiu?</h2></div><CircleDollarSign className="size-8" /></div><div className="mt-7 grid gap-3"><Button onClick={() => openEntry("gain")} className="h-16 justify-between rounded-2xl bg-[#11251f] px-5 text-base font-black text-white"><span className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#c8ff39] text-[#11251f]"><Plus /></span>Registrar ganho</span><ChevronRight /></Button><Button onClick={() => openEntry("expense")} variant="outline" className="h-16 justify-between rounded-2xl border-[#11251f]/15 bg-white/55 px-5 text-base font-black"><span className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-white"><ReceiptText /></span>Registrar gasto</span><ChevronRight /></Button></div><p className="mt-5 flex items-center gap-2 text-sm font-semibold text-[#3d3514]/65"><Check className="size-4" /> Leva menos de 30 segundos.</p></section>
  </div><div className="mt-5 grid gap-5 xl:grid-cols-[1.25fr_1fr]"><section className="rounded-[28px] bg-white p-5 shadow-sm sm:p-7"><SectionTitle eyebrow="PARA ONDE FOI O DINHEIRO" title="Custos de hoje" /><div className="mt-7 space-y-5"><Cost icon={Fuel} label="Combustível" detail="Registrado hoje" value={90} total={totalCosts} color="#ffb62e" /><Cost icon={Wrench} label="Manutenção" detail={`${money(state.maintenancePerKm)} por km`} value={summary.km * state.maintenancePerKm} total={totalCosts} color="#52a7ff" /><Cost icon={CarFront} label="Desgaste do carro" detail={`${money(state.depreciationPerKm)} por km`} value={summary.km * state.depreciationPerKm} total={totalCosts} color="#9f7aea" /><Cost icon={WalletCards} label="Custos fixos" detail="Seguro, IPVA e outros" value={summary.fixed} total={totalCosts} color="#ef6d77" /></div></section><section className="rounded-[28px] bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center justify-between"><SectionTitle eyebrow="SEUS APLICATIVOS" title="Ganhos de hoje" /><BarChart3 className="size-6 text-[#718079]" /></div><div className="mt-7 space-y-4"><AppRow name="Uber" amount={184} total={summary.gains} color="#11251f" /><AppRow name="99" amount={136} total={summary.gains} color="#ff4458" /><AppRow name="inDrive" amount={0} total={summary.gains} color="#9de22e" /></div><div className="mt-7 rounded-2xl bg-[#f3f5f2] p-4"><p className="text-xs font-black uppercase tracking-wider text-[#718079]">Melhor turno recente</p><p className="mt-1 text-lg font-black">Terça, 17h–21h</p><p className="text-sm font-semibold text-[#65756e]">{money(25.8)}/h · baseado em 4 turnos</p></div></section></div></>;
}
function DarkMetric({ label, value, icon: Icon, tone }: { label: string; value: string; icon: typeof Clock3; tone?: string }) { return <div><div className={`mb-2 grid size-8 place-items-center rounded-xl ${tone === "lime" ? "bg-[#c8ff39]/15 text-[#c8ff39]" : tone === "amber" ? "bg-[#ffd44d]/15 text-[#ffd44d]" : "bg-white/8 text-white/60"}`}><Icon className="size-4" /></div><p className="text-xs font-bold text-white/45">{label}</p><p className="mt-0.5 text-lg font-black">{value}</p></div>; }
function Cost({ icon: Icon, label, detail, value, total, color }: { icon: typeof Fuel; label: string; detail: string; value: number; total: number; color: string }) { return <div className="grid grid-cols-[42px_1fr_auto] items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-[#f3f5f2]"><Icon className="size-5" /></div><div><p className="font-black">{label}</p><p className="text-xs font-semibold text-[#7a8882]">{detail}</p><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[#edf0ee]"><div className="h-full rounded-full" style={{ width: `${total ? Math.min(100, value / total * 100) : 0}%`, background: color }} /></div></div><p className="font-black">{money(value)}</p></div>; }
function AppRow({ name, amount, total, color }: { name: string; amount: number; total: number; color: string }) { return <div className="grid grid-cols-[42px_1fr_auto] items-center gap-3"><div className="grid size-10 place-items-center rounded-xl text-sm font-black text-white" style={{ background: color }}>{name[0]}</div><div><p className="font-black">{name}</p><div className="mt-1.5 h-2 overflow-hidden rounded-full bg-[#edf0ee]"><div className="h-full rounded-full" style={{ width: `${total ? amount / total * 100 : 0}%`, background: color }} /></div></div><p className="font-black">{money(amount)}</p></div>; }

function HistoryView({ state }: { state: AppState }) { const groups = [...new Set(state.entries.map(e => e.date))].sort().reverse(); return <section><PageHeading eyebrow="SEUS REGISTROS" title="Histórico financeiro" description="Confira o que entrou, saiu e quanto sobrou em cada dia." /><div className="grid gap-5 xl:grid-cols-[1.5fr_.7fr]"><div className="space-y-4">{groups.map(date => { const day = summaryOf(state, date); return <div key={date} className="rounded-[24px] bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#edf0ee] pb-4"><div><p className="text-sm font-bold text-[#718079]">{shortDate(date)}</p><p className="text-xl font-black">Lucro estimado {money(Math.max(0, day.profit))}</p></div><span className="rounded-full bg-[#e9f8d5] px-3 py-1.5 text-sm font-black text-[#315f19]">{day.hours.toFixed(1)}h · {day.km} km</span></div><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4"><Small label="Ganhos" value={money(day.gains)} /><Small label="Gastos" value={money(day.expenses)} /><Small label="Por hora" value={money(day.hours ? day.profit / day.hours : 0)} /><Small label="Por km" value={money(day.km ? day.profit / day.km : 0)} /></div></div>; })}</div><aside className="h-fit rounded-[24px] bg-[#11251f] p-6 text-white"><CalendarDays className="size-7 text-[#c8ff39]" /><p className="mt-8 text-sm font-bold text-white/50">SETEMBRO</p><p className="mt-1 text-4xl font-black tracking-[-.05em]">{money(1884)}</p><p className="mt-2 text-sm font-semibold text-white/60">Lucro estimado no mês</p><div className="mt-6 grid grid-cols-2 gap-3"><DarkSmall label="Dias" value="18" /><DarkSmall label="Média/dia" value={money(104.67)} /></div></aside></div></section>; }
function MeiView({ revenue }: { revenue: number }) { const limit = 81000, p = Math.min(100, revenue / limit * 100); return <section><PageHeading eyebrow="ORGANIZAÇÃO FISCAL" title="Meu MEI" description="Acompanhe vencimentos e faturamento sem misturar receita com lucro." /><div className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><div className="rounded-[28px] bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold text-[#718079]">FATURAMENTO REGISTRADO EM 2026</p><p className="mt-2 text-4xl font-black tracking-[-.05em]">{money(revenue)}</p><p className="mt-2 font-semibold text-[#718079]">de {money(limit)} do limite configurado</p></div><span className="rounded-full bg-[#e9f8d5] px-3 py-2 text-sm font-black text-[#315f19]">{p.toFixed(0)}% usado</span></div><Progress value={p} className="mt-7 h-4 bg-[#e9edeb] [&_[data-slot=progress-indicator]]:bg-[#5cbd60]" /><div className="mt-8 grid gap-3 sm:grid-cols-3"><Small label="Disponível" value={money(limit - revenue)} /><Small label="Média mensal" value={money(revenue / 9)} /><Small label="Projeção anual" value={money(revenue / 9 * 12)} /></div><div className="mt-8 rounded-2xl border border-[#f0d676] bg-[#fff8d8] p-4"><p className="font-black">Atenção à projeção</p><p className="mt-1 text-sm font-semibold text-[#6c5b24]">Revise receitas de outros trabalhos antes de declarar.</p></div></div><aside className="space-y-5"><div className="rounded-[28px] bg-[#ffd44d] p-6"><p className="text-sm font-black text-[#5c4d15]">PRÓXIMO DAS</p><p className="mt-3 text-4xl font-black">R$ 86,05</p><p className="mt-1 font-semibold text-[#5c4d15]">Vence em 20 de outubro</p><Button className="mt-6 h-12 w-full rounded-2xl bg-[#11251f] font-black text-white">Abrir portal oficial</Button></div><div className="rounded-[28px] bg-white p-6 shadow-sm"><p className="font-black">Checklist do mês</p><div className="mt-4 space-y-3"><CheckItem done text="Receitas conferidas" /><CheckItem done text="DAS de setembro pago" /><CheckItem text="Guardar comprovantes" /><CheckItem text="Baixar relatório mensal" /></div></div></aside></div></section>; }
function SettingsView({ state, onChange }: { state: AppState; onChange: (next: AppState) => void }) { const [draft, setDraft] = useState(state); return <section><PageHeading eyebrow="SUA CONTA" title="Configurações" description="Ajuste os custos para deixar a estimativa mais próxima da sua realidade." /><div className="grid gap-5 xl:grid-cols-2"><SettingsCard title="Veículo e custos" icon={CarFront}><Field label="Seu carro"><Input value={draft.vehicle} onChange={e => setDraft({ ...draft, vehicle: e.target.value })} /></Field><div className="grid grid-cols-2 gap-3"><Field label="Manutenção por km"><Input type="number" step=".01" value={draft.maintenancePerKm} onChange={e => setDraft({ ...draft, maintenancePerKm: Number(e.target.value) })} /></Field><Field label="Desgaste por km"><Input type="number" step=".01" value={draft.depreciationPerKm} onChange={e => setDraft({ ...draft, depreciationPerKm: Number(e.target.value) })} /></Field></div><Field label="Custos fixos mensais"><Input type="number" value={draft.monthlyFixed} onChange={e => setDraft({ ...draft, monthlyFixed: Number(e.target.value) })} /></Field></SettingsCard><SettingsCard title="Metas de lucro" icon={Target}><Field label="Meta diária"><Input type="number" value={draft.dailyGoal} onChange={e => setDraft({ ...draft, dailyGoal: Number(e.target.value) })} /></Field><Field label="Meta semanal"><Input type="number" value={draft.weeklyGoal} onChange={e => setDraft({ ...draft, weeklyGoal: Number(e.target.value) })} /></Field><Field label="Receita anterior ao app neste ano"><Input type="number" value={draft.annualRevenueBeforeApp} onChange={e => setDraft({ ...draft, annualRevenueBeforeApp: Number(e.target.value) })} /></Field></SettingsCard></div><Button onClick={() => { onChange(draft); toast.success("Configurações salvas"); }} className="mt-5 h-13 rounded-2xl bg-[#11251f] px-7 font-black text-white">Salvar configurações</Button><div className="mt-8 grid gap-3 sm:grid-cols-3"><Preference icon={Bell} title="Lembretes" text="Resumo às 21h" /><Preference icon={FileText} title="Meus dados" text="Exportar ou excluir" /><Preference icon={WalletCards} title="Plano" text="Completo · ativo" /></div></section>; }

function EntryDialog({ open, type, onTypeChange, onOpenChange, onSave }: { open: boolean; type: "gain" | "expense"; onTypeChange: (v: "gain" | "expense") => void; onOpenChange: (v: boolean) => void; onSave: (e: Omit<Entry, "id">) => void }) {
  const [amount, setAmount] = useState(""), [category, setCategory] = useState("Combustível"), [app, setApp] = useState("Uber"), [km, setKm] = useState(""), [hours, setHours] = useState("");
  const submit = () => { const value = Number(amount.replace(",", ".")); if (!value || value <= 0) return void toast.error("Informe um valor maior que zero"); onSave({ type, amount: value, category: type === "gain" ? "Corridas" : category, app: type === "gain" ? app : undefined, date: today, km: Number(km) || undefined, hours: Number(hours) || undefined }); setAmount(""); setKm(""); setHours(""); onOpenChange(false); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto rounded-[26px] border-0 p-0 sm:max-w-[540px]"><div className="bg-[#11251f] p-6 text-white"><DialogHeader><DialogTitle className="text-2xl font-black">Novo lançamento</DialogTitle><DialogDescription className="text-white/55">Registre com o carro parado. Você pode corrigir depois.</DialogDescription></DialogHeader></div><div className="p-6"><Tabs value={type} onValueChange={v => onTypeChange(v as "gain" | "expense")}><TabsList className="grid h-12 w-full grid-cols-2 rounded-2xl bg-[#edf1ee] p-1"><TabsTrigger value="gain" className="rounded-xl font-black data-[state=active]:bg-[#c8ff39]">Ganho</TabsTrigger><TabsTrigger value="expense" className="rounded-xl font-black data-[state=active]:bg-[#ffd44d]">Gasto</TabsTrigger></TabsList><TabsContent value="gain" className="mt-6 space-y-4"><Field label="Aplicativo"><div className="grid grid-cols-3 gap-2">{["Uber", "99", "inDrive"].map(n => <button key={n} onClick={() => setApp(n)} className={`h-12 rounded-xl border text-sm font-black ${app === n ? "border-[#11251f] bg-[#11251f] text-white" : "border-[#dce2dd]"}`}>{n}</button>)}</div></Field><div className="grid grid-cols-2 gap-3"><Field label="Horas"><Input type="number" step=".1" value={hours} onChange={e => setHours(e.target.value)} placeholder="8" /></Field><Field label="Km de trabalho"><Input type="number" value={km} onChange={e => setKm(e.target.value)} placeholder="180" /></Field></div></TabsContent><TabsContent value="expense" className="mt-6"><Field label="Categoria"><div className="grid grid-cols-2 gap-2">{["Combustível", "Manutenção", "Pedágio", "Outros"].map(n => <button key={n} onClick={() => setCategory(n)} className={`h-11 rounded-xl border text-sm font-black ${category === n ? "border-[#11251f] bg-[#11251f] text-white" : "border-[#dce2dd]"}`}>{n}</button>)}</div></Field></TabsContent></Tabs><Field label="Valor"><div className="mt-1 flex items-center rounded-2xl border border-[#cfd7d2] px-4 focus-within:ring-2"><span className="text-xl font-black text-[#6c7b74]">R$</span><input className="h-16 min-w-0 flex-1 bg-transparent px-3 text-3xl font-black outline-none" inputMode="decimal" value={amount} onChange={e => setAmount(e.target.value)} placeholder="0,00" /></div></Field><Button onClick={submit} className="mt-6 h-14 w-full rounded-2xl bg-[#c8ff39] text-base font-black text-[#11251f]">Salvar lançamento</Button></div></DialogContent></Dialog>;
}
function SectionTitle({ eyebrow, title }: { eyebrow: string; title: string }) { return <div><p className="text-sm font-bold text-[#718079]">{eyebrow}</p><h2 className="text-xl font-black">{title}</h2></div>; }
function PageHeading({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div className="mb-7"><p className="text-sm font-black tracking-wider text-[#6d7b75]">{eyebrow}</p><h1 className="mt-1 text-3xl font-black tracking-[-.045em] sm:text-4xl">{title}</h1><p className="mt-2 max-w-2xl font-semibold text-[#6d7b75]">{description}</p></div>; }
function Small({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-[#f3f5f2] p-4"><p className="text-xs font-black text-[#73817b]">{label}</p><p className="mt-1 font-black">{value}</p></div>; }
function DarkSmall({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-white/7 p-3"><p className="text-xs font-bold text-white/45">{label}</p><p className="mt-1 font-black">{value}</p></div>; }
function CheckItem({ done = false, text }: { done?: boolean; text: string }) { return <div className="flex items-center gap-3 text-sm font-bold"><span className={`grid size-6 place-items-center rounded-full ${done ? "bg-[#c8ff39]" : "border-2 border-[#dbe1dd]"}`}>{done && <Check className="size-4" />}</span>{text}</div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block py-2"><span className="mb-2 block text-sm font-black text-[#596861]">{label}</span>{children}</label>; }
function SettingsCard({ title, icon: Icon, children }: { title: string; icon: typeof CarFront; children: React.ReactNode }) { return <div className="rounded-[28px] bg-white p-6 shadow-sm"><div className="mb-5 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#e9f8d5]"><Icon className="size-5" /></span><h2 className="text-xl font-black">{title}</h2></div>{children}</div>; }
function Preference({ icon: Icon, title, text }: { icon: typeof Bell; title: string; text: string }) { return <button className="flex items-center gap-3 rounded-2xl bg-white p-4 text-left shadow-sm"><span className="grid size-10 place-items-center rounded-xl bg-[#f3f5f2]"><Icon className="size-5" /></span><span><span className="block font-black">{title}</span><span className="text-sm font-semibold text-[#718079]">{text}</span></span><ChevronRight className="ml-auto size-5 text-[#87928d]" /></button>; }
